### PR TITLE
Pipeline support

### PR DESCRIPTION
**Pull request by lance513**
Dependency Graph View now also shows Pipeline Jobs with its dependencies (as well as all other job types which implement jenkins.model.ParameterizedJobMixIn.ParameterizedJob and make use of jenkins.triggers.ReverseBuildTrigger).

The following changes were necessary:
* in pom:
  * the plugin now uses the most recent plugin-pom as parent
  * min jenkins version set to 2.100 and java version set to 8
  * using artifact org.google.inject.extensions.guice-multibindings instead of org.sonatype.sisu.inject.guice-multibindings since sonatype version is marked as banned in parent pom
  * removed several dependencies from pom since they are defined in parent pom
* in code:
  * replaced most references of type AbstractProject with type ParameterizedJob since Pipeline jobs (class org.jenkinsci.plugins.workflow.job.WorkflowJob) do not inherit AbstractProject
  * since dependencies of Pipeline jobs are not reflected in hudson.model.DependencyGraph, added new class ReverseBuildTriggerEdgeProvider which
    * adds an edge from each project which is mentioned as ReverseBuildTrigger within the currently considered project (upstream)
    * adds an edge to each project where the currently considered project is mentioned as ReverseBuildTrigger (downstream)
  * minor changes like replacing deprecated method calls

### CODE REVIEW

**Comment by wolfs** [comment]
@lance513 Thank you for your PR. Note that this plugin does currently not have a maintainer, so I am not sure if anybody will look at this PR or merge it.

**Comment by lance513** [comment]
That is sad, I really like this plugin. And it supporting pipeline projects might be very useful for others as well.
What would I have to do to become a maintainer?

**Comment by wolfs** [comment]
Check out this documentation on adopting a plugin: https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin

**Comment by stevenschlansker** [comment]
I would love to see this feature released as well, just came here researching why none of my projects were graphing, I was excited to use this plugin...

**Comment by guidograzioli** [comment]
@lance513 thanks for your work, I'll merge it; but this is definitely a too big PR which touches many other things than adding pipeline support

**Pull request merged**
